# Generated by Django 2.1.4 on 2019-11-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSConst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=150, unique=True)),
                ('hs_type', models.CharField(max_length=150)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('is_new', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StockBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=150, unique=True)),
                ('symbol', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=150)),
                ('fullname', models.CharField(max_length=150)),
                ('ename', models.CharField(max_length=150)),
                ('market', models.CharField(max_length=150)),
                ('exchange', models.CharField(max_length=150)),
                ('curr_type', models.CharField(max_length=100)),
                ('list_status', models.CharField(max_length=50)),
                ('list_date', models.CharField(max_length=150)),
                ('delist_date', models.CharField(max_length=150)),
                ('is_hs', models.CharField(max_length=50)),
            ],
        ),
    ]
