# Generated by Django 2.1.4 on 2019-11-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbasic',
            old_name='ename',
            new_name='enname',
        ),
    ]
