# Generated by Django 2.1.4 on 2019-11-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdatabase', '0003_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBasic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('index_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('base_date', models.CharField(max_length=100)),
                ('base_point', models.CharField(max_length=100)),
                ('list_date', models.CharField(max_length=100)),
                ('weight_rule', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('exp_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='daily',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
